# vi: ft=dockerfile

FROM centos:7

WORKDIR /root

COPY example example

RUN yum -y install \
            gcc \
            libffi-devel \
            make \
            rpmdevtools \
            ruby \
            ruby-devel \
            && rm -rf /var/cache/yum/*

RUN gem install fpm

RUN fpm -s dir -t rpm -n hello-world -v 0.0.1 example/hello-world=/usr/bin/hello-world

RUN rpm -i hello-world*.rpm

CMD ["/usr/bin/hello-world"]
