# vi: ft=dockerfile

FROM centos:6 as builder

WORKDIR /root

COPY example example

RUN yum -y install \
            curl \
            gcc \
            git \
            libyaml-devel \
            patch \
            rpmdevtools \
            ruby-devel \
            zlib-devel \
            && rm -rf /var/cache/yum/*

RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.5.0

RUN echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc && echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc

SHELL ["/bin/bash", "-lc"]

RUN asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

RUN asdf install ruby 1.9.3-p551

RUN asdf global ruby 1.9.3-p551

RUN gem install fpm

RUN ln -s /root/.asdf/installs/ruby/1.9.3-p551/bin/fpm /usr/local/bin/fpm

RUN fpm -s dir -t rpm -n hello-world -v 0.0.1 example/hello-world=/usr/bin/hello-world

RUN rpm -i hello-world*.rpm

CMD ["/usr/bin/hello-world"]
